console.log(' '+' '+' '+' '+' '+' '+' '+' '+"%c$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+"%c$$$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+"%c$$$$$$$$",'color:#0f0');
console.log(' '+' '+' '+"%c$$$$$$$$$$$$$",'color:#0f0');
console.log(' '+' '+"%c$$$$$$$$$$$$$$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+"%c$$$$$$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+"%c$$$$$$$$$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+"%c$$$$$$$$$$$$$$",'color:#0f0');
console.log(' '+' '+' '+' '+"%c$$$$$$$$$$$$$$$$",'color:#0f0');
console.log(' '+' '+' '+"%c$$$$$$$$$$$$$$$$$$",'color:#0f0');
console.log(' '+' '+"%c$$$$$$$$$$$$$$$$$$$$$",'color:#0f0');
console.log(' '+"%c$$$$$$$$$$$$$$$$$$$$$$$$",'color:#0f0');
console.log("%c$$$$$$$$$$$$$$$$$$$$$$$$$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
console.log(' '+' '+' '+' '+' '+' '+' '+' '+' '+"%c$$$",'color:#0f0');
$("#agritourismSearch").click(function() {
	$("body")[0].style.backgroundColor = "#00FF00";
});
